### PR TITLE
Add option for choosing rmw fill method

### PR DESCRIPTION
**Pull request by SorooshMani-NOAA**
Defaults to PSurge v2.9 method.

### CODE REVIEW

**Comment by SorooshMani-NOAA** [comment]
@WPringle I'm not sure if it'd be helpful or not to accept `str` type as input or we should leave it to the user to import the `RMWFillMethod` and pass the write enum. Otherwise this seems to be working fine.

Also I was wondering what you think about the names `none`, `persistent` and `psurge_v2_9`?

I defaulted it to be the new psurge method.

Please let me know what you think ... I'll add some tests soon

**Comment by WPringle** [comment]
@SorooshMani-NOAA Thank you! The `psurge_v2_9` naming is the one I'm unsure about as it is not clear at first what it means. On the other hand it is specific, which is good. Could do: `regression_psurge2_9` or something like that?

**Comment by SorooshMani-NOAA** [comment]
@WPringle I also would like it to be short, so maybe `penny_etal_2023`? Let's bring it up in the psurge dev meeting

**Comment by SorooshMani-NOAA** [comment]
Other name suggestions discussed:
- `penny_2023`
- `rmw_regression`
- `regression_penny_etal_2023`

I agree that having `regression` in the name says what is happening, like `persistent` says **persistent** but, then `penny_2023` is much shorter and more exact. I'll give it more thought and if I didn't get any more feedback (either in the internal chat or here) I'll probably go with `penny_2023`. 

By the way @WPringle having only `regression` could also mean future "regression" methods need to be named `regression_2`, `_3`, etc. So having paper ref is much better, but also I think having both "regression" and paper ref in the name is just too long to type! 😆

**Pull request merged**
