### PR TITLE
Bug fix/quadrant order

### PR DESCRIPTION
**Pull request by WPringle**
quadrant order is clockwise from NE, i.e., NE, SE, SW, NW. 
SW and NW were in the wrong order.

### CODE REVIEW

**Comment by SorooshMani-NOAA** [comment]
@WPringle is this going to have impact on the GAHM results? I think we can get rid of repr tests and put the into a single separate test that doesn't run on macos, it seems macos has different `repr` for int type compared to linux.

**Comment by WPringle** [comment]
@SorooshMani-NOAA It should not have an impact as currently implemented since it keeps the order in the file it is read from. But it is referencing the wrong quadrant which I am using to figure out some prediction of isotach radii in EnsemblePerturbation.

**Comment by WPringle** [comment]
@SorooshMani-NOAA I'm getting all passing tests on Argonne linux machine, python 3.10.

**Comment by SorooshMani-NOAA** [comment]
I get all pass on linux too. Something weird is happening on macos, that's why I want it to be tested on a macos. I don't have access to one to see what's going on. I thought you might!

**Comment by SorooshMani-NOAA** [comment]
@WPringle I actually see the issue in Linux too on this CI test!! I think we need to update the tests in the future. If everything passes on your machine we can go through with this and later create a PR for fixing tests!

**Comment by WPringle** [comment]
@SorooshMani-NOAA Yeah I'm fine to merge this and add issue/PR for fixing tests.

**Pull request merged**
