### PR TITLE
corrections to paddings in track.to_file

### PR DESCRIPTION
**Pull request by WPringle**
correcting incorrect padding of vmax fort ATCF and incorrect padding for lon, lat, gust, direction for fort.22

### CODE REVIEW

**Comment by WPringle** [comment]
> @WPringle before proceeding with updating all the outdated test reference files, I just want to make sure I understand correctly. So there are two main changes here:
> 
> 1. The padding for ATCF maximum wind is changed from 5 to 4 (for both `.22` and `.dat` formats)
> 2. The following fields will have the same padding in both `.22` and `.dat` formats
>    
>    * longitude -> 6
>    * latitude -> 5
>    * gust_speed -> 4
>    * direction -> 4
> 
> Right?

Yeah I don't think fort.22 and atcf should really be any different, except seems like fort.22 has some numbers at the end.

**Comment by WPringle** [comment]
@SorooshMani-NOAA I have confirmed that the output from these changes works correctly with ADCIRC storm prepping `aswip` utility.

**Comment by SorooshMani-NOAA** [comment]
@WPringle thanks a lot, I appreciate it

**Comment by SorooshMani-NOAA** [comment]
@WPringle please review the updated test references padding in the diff tab and proceed with the merging if everything looks fine. Thanks!

**Pull request merged**
