### PR TITLE
fix in reading date time from ATCF file

### PR DESCRIPTION
**Pull request by WPringle**
adding forecast time to datetime which is the correct record time is unnecessary

### CODE REVIEW

**Comment by zacharyburnettNOAA** [comment]
I checked and `forecast_hours` isn't used anywhere else, but should it be being applied somewhere?

**Comment by WPringle** [comment]
> I checked and `forecast_hours` isn't used anywhere else, but should it be being applied somewhere?

But it's written out to the ATCF file right? Maybe it's already computed automatically within code?

**Comment by zacharyburnettNOAA** [comment]
ah ok, the current code only outputs `fort.22` files; if we wanted to also output ATCF files (which is probably a good idea) then we'll need to keep the forecast hours in the dataframe somehow

**Comment by WPringle** [comment]
> ah ok, the current code only outputs `fort.22` files; if we wanted to also output ATCF files (which is probably a good idea) then we'll need to keep the forecast hours in the dataframe somehow

But it's also the 5th column of `fort.22` files (it's reading in from fort.22 here)

**Comment by zacharyburnettNOAA** [comment]
> But it's also the 5th column of fort.22 files (it's reading in from fort.22 here)

oh you're absolutely right, I was being dumb

I'll write up something to add forecast hours to the stored dataframe and carry that over to the written file; it looks like it is currently doing the following for writing the `forecast_hours` column: 
https://github.com/oceanmodeling/StormEvents/blob/f0c0948f00660ad9a3458111d0b2166eb1a6218c/stormevents/nhc/track.py#L576

**Pull request merged**
